import CustomThemeProvider from "@/components/providers/CustomThemeProvider";
import "../globals.css";
import { cookies } from "next/headers";
import Navbar from "@/components/Layout/dashboard/Navbar";
import { Suspense } from "react";
import Loading from "./loading";
export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const token = cookies().get("seller_token")?.value;
  return (
    <html lang="en">
      <body>
        <CustomThemeProvider>
          <Suspense fallback={<Loading />}>
            <Navbar token={token} />
            {children}
          </Suspense>
        </CustomThemeProvider>
      </body>
    </html>
  );
}
