import CustomThemeProvider from "@/components/providers/CustomThemeProvider";
import "../globals.css";
import { cookies } from "next/headers";
import { Suspense } from "react";
import Loading from "./loading";
import Navbar from "@/components/Layout/Navbar";
import Footer from "@/components/Layout/Footer";
import { redirect } from "next/navigation";
export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const sellerToken = cookies().get("seller_token")?.value ?? null;
  const token = cookies().get("token")?.value ?? null;
  if (!token) redirect("/login");
  return (
    <html lang="en">
      <body>
        <CustomThemeProvider>
          <Suspense fallback={<Loading />}>
            <Navbar token={token} sellerToken={sellerToken} />
            {children}
            <Footer />
          </Suspense>
        </CustomThemeProvider>
      </body>
    </html>
  );
}
