import { Suspense } from "react";
import Loading from "./loading";
import { cookies } from "next/headers";
import { redirect } from "next/navigation";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const token = cookies().get("token")?.value ?? null;
  if (!token) redirect("/login");
  return <Suspense fallback={<Loading />}>{children}</Suspense>;
}
