import "../globals.css";
import CustomThemeProvider from "@/components/providers/CustomThemeProvider";
import { Suspense } from "react";
import Loading from "../(auth)/loading";
import Navbar from "@/components/Layout/Navbar";
import { cookies } from "next/headers";
import { Montserrat } from "next/font/google";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

const montserrat = Montserrat({ subsets: ["latin"] });

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const sellerToken = cookies().get("seller_token")?.value ?? null;
  return (
    <html lang="en">
      <body className={montserrat.className}>
        <CustomThemeProvider>
          <Suspense fallback={<Loading />}>
            <Navbar sellerToken={sellerToken} />
            {children}
          </Suspense>
        </CustomThemeProvider>
      </body>
    </html>
  );
}
