import { Suspense } from "react";
import Loading from "./loading";
import { cookies } from "next/headers";
import { redirect } from "next/navigation";
import Sidebar from "@/components/Layout/Sidebar";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const token = cookies().get("token")?.value ?? null;
  if (!token) redirect("/login");
  return (
    <>
      <Suspense fallback={<Loading />}>
        <div className="pt-[70px] bg-[#F5F5F5] min-h-[70vh]">
          <div className="px-[30px] lg:px-[50px] ">
            <div className="container flex gap-4 my-10">
              <Sidebar />
              <div className="flex-1">{children}</div>
            </div>
          </div>
        </div>
      </Suspense>
    </>
  );
}
