import { Montserrat } from "next/font/google";
import Sidebar from "@/components/Layout/dashboard/Sidebar";
import { cookies } from "next/headers";
import { redirect } from "next/navigation";

const montserrat = Montserrat({ subsets: ["latin"] });
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const token = cookies().get("seller_token")?.value;
  if (!token) redirect("/shop-login");
  return (
    <>
      <div className="flex bg-[#f4f4f4] min-h-[calc(100vh-70px)] relative">
        <Sidebar />
        <div className="flex-1 m-5 w-full h-[85vh] overflow-y-auto hide-scroll">
          <div className="container">{children}</div>
        </div>
      </div>
    </>
  );
}
