import "../globals.css";
import { Montserrat } from "next/font/google";
import CustomThemeProvider from "@/components/providers/CustomThemeProvider";
import { cookies } from "next/headers";
import { Suspense } from "react";
import Loading from "./loading";
import { redirect } from "next/navigation";
import Navbar from "@/components/Layout/dashboard/Navbar";
import "react-widgets/styles.css";

const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function DashboardLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const token = cookies().get("seller_token")?.value ?? null;
  if (!token) redirect("/shop/login");
  return (
    <html lang="en">
      <body className={montserrat.className}>
        <CustomThemeProvider>
          <Suspense fallback={<Loading />}>
            <Navbar token={token} />
            {children}
          </Suspense>
        </CustomThemeProvider>
      </body>
    </html>
  );
}
